apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: 676802897789.dkr.ecr.us-east-1.amazonaws.com/todo-server:latest # Sets Image
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080  # Exposes container port
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/bash","-c","sleep 120" ]
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"