apiVersion: v1
kind: Service
metadata:
  name: todo-backend # Sets service name
  labels:
    app: todo-backend # Labels and Selectors
spec:
  type: LoadBalancer # Sets service type
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: todo-backend